.gitignore
README.md
src/main/java/org/librespot/spotify/AbsConfiguration.java
src/main/java/org/librespot/spotify/DefaultConfiguration.java
src/main/java/org/librespot/spotify/Main.java
src/main/java/org/librespot/spotify/core/Session.java
src/main/java/org/librespot/spotify/player/AudioFile.java
src/main/java/org/librespot/spotify/player/AudioFileFetch.java
src/main/java/org/librespot/spotify/player/AudioFileStreaming.java
src/main/java/org/librespot/spotify/player/CacheManager.java
src/main/java/org/librespot/spotify/player/ChannelManager.java
src/main/java/org/librespot/spotify/player/NormalizationData.java
src/main/java/org/librespot/spotify/player/Player.java
src/main/java/org/librespot/spotify/player/PlayerRunner.java

Implemented a cache for the client. 
N.B.
- This is not compatible with the original Spotify cache
- The first 4 bytes of the cache make up an int which is the size of the track divided by 4
- ~Arbitrarily deleting files from the cache will break it~ (c278acdd3ca5e90158b1886810aba4cf273ebedd)

Cache implementation

---

.travis.yml
conf.properties
core/src/main/java/xyz/gianlu/librespot/AbsConfiguration.java
core/src/main/java/xyz/gianlu/librespot/DefaultConfiguration.java
core/src/main/java/xyz/gianlu/librespot/FileConfiguration.java
core/src/main/java/xyz/gianlu/librespot/core/Session.java
core/src/main/java/xyz/gianlu/librespot/core/ZeroconfAuthenticator.java

interfaces, without including loopback addresses.  This fixed #32 for me, while the previous fix did not.

Fix for #32 - correctly advertise IP Addresses for multiple network

---

core/src/main/java/xyz/gianlu/librespot/player/PlayerRunner.java

This fixes a crash on Windows (didn't test on another operating system) when the first mixer wasn't supported.

Iterate through the mixers and select one that's supported

---

core/src/main/java/xyz/gianlu/librespot/player/Player.java
core/src/main/java/xyz/gianlu/librespot/player/TrackHandler.java

Fixes couple of seconds playback of progress bar before resetting itself once song is actually loaded. If anyone has a slow connection, please test.

Send loading event the moment librespot-java calls load()

---

core/src/main/java/xyz/gianlu/librespot/spirc/SpotifyIrc.java

This should get you started - the load events should reach the client now.
It now crashes with:
```shell
2019-03-30 23:17:02 DEBUG Player:358 - Loading context, uri: spotify:show:09Rlb3I3tzqeI5KRLDTyOb
Exception in thread "handle-packet-1338357277" java.lang.IllegalArgumentException: Not a Spotify track ID: spotify:episode:2seDhYwSEWURmEUYimIxn5
at xyz.gianlu.librespot.mercury.model.TrackId.fromUri(TrackId.java:32)
at xyz.gianlu.librespot.player.remote.Remote3Track.id(Remote3Track.java:41)
at xyz.gianlu.librespot.player.remote.Remote3Track.toTrackRef(Remote3Track.java:36)
at xyz.gianlu.librespot.player.Player$StateWrapper.update(Player.java:604)
at xyz.gianlu.librespot.player.Player.updatedTracks(Player.java:269)
at xyz.gianlu.librespot.player.Player.handleLoad(Player.java:360)
at …
```

Let Spotify know the client supports podcasts

---

interactive-cli/pom.xml

I've had the repo cloned for some time and after pulling the last changes "maven clean package" was giving me compile error only for interactive-cli:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project interactive-cli: Compilation failure
[ERROR] /Users/admin/Documents/librespot-java/interactive-cli/src/main/java/xyz/gianlu/librespot/interactivecli/Main.java:[82,33] constructor FileConfiguration in class xyz.gianlu.librespot.FileConfiguration cannot be applied to given types;
[ERROR]   required: java.io.File,java.lang.String[]
[ERROR]   found: java.lang.String[]
[ERROR]   reason: actual and formal argument lists differ in length
```
Which was weird because CI was passing. Right?
Then I looked closer to maven output: …

Update interactive-cli pom.xml

---

.gitignore
core/src/main/java/xyz/gianlu/librespot/FileConfiguration.java
core/src/main/java/xyz/gianlu/librespot/Version.java

```arg.substring(13)``` should start from index 12. Because "--conf-file=" length is 12, So it occupies index 0 through 11 and everything after is the file name.

Fix problem regarding using a custom named options file

---

api/src/main/java/xyz/gianlu/librespot/api/Main.java
api/src/main/java/xyz/gianlu/librespot/api/server/ApiServer.java
api/src/main/java/xyz/gianlu/librespot/api/server/ZeroconfApiServer.java
core/src/main/java/xyz/gianlu/librespot/core/ZeroconfServer.java

I noticed the Zeroconf server couldn't be used with the ApiServer. This PR adds that functionality.
Changes:
- ZeroconfServer now has a interface SessionListener, to notify any listeners for a Session change
- ZeroconfServer now contains a list of SessionListener; notifies listeners when a new Session is authenticated
- Add method ApiServer.clearHandlers(); clears the ApiHandlers Map when a new Session is presented
- Add class ZeroconfApiServer, extends ApiServer implements SessionListener; listens for changes in the ZeroconfServer's Session, clears old request handlers and registers new ones when a new Session is presented

Zeroconf ApiServer

---

core/src/main/java/xyz/gianlu/librespot/core/ZeroconfServer.java

ZeroconfServer Doesn't compile with StandardCharsets.UTF_8 in Java 11.
`java: incompatible types: java.nio.charset.Charset cannot be converted to java.lang.String`.
URL parameters should be of String type.

Hotfix ZeroconfServer not compiling

---

api/pom.xml
api/src/main/java/xyz/gianlu/librespot/api/ApiServer.java

This adds CORS Headers to allow usage from browser based web apps:
**without** header *Origin*
```
$ curl -XPOST 'http://localhost:24879/metadata/track/spotify:track:4lXt6ROo0I3U7p3loYQX5U' -v | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:24879...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 24879 (#0)
> POST /metadata/track/spotify:track:4lXt6ROo0I3U7p3loYQX5U HTTP/1.1
> Host: localhost:24879
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Length: 1457
< Date: Mon, 16 Dec 2019 00:07:06 GMT
```
**with** header …

adds CorsHeaders to allow usage from javascript

---

common/src/main/java/xyz/gianlu/librespot/common/Utils.java
core/src/main/java/xyz/gianlu/librespot/AbsConfiguration.java
core/src/main/java/xyz/gianlu/librespot/FileConfiguration.java
core/src/main/java/xyz/gianlu/librespot/core/Session.java
core/src/main/resources/default.toml

In my situation, I create multiple instances of librespot-java and each instance can randomly appear & disappear. 
To avoid confusion with the deviceId's (mdns), I have to set a persistent deviceId for each instance so an instance doesn't appear twice with the same name and different deviceId.
Please allow to set a permantent deviceId.

Make device id configurable

---

.travis.yml
core/src/main/java/xyz/gianlu/librespot/mercury/model/ImageId.java
core/src/main/java/xyz/gianlu/librespot/player/Player.java
core/src/main/java/xyz/gianlu/librespot/player/PlayerRunner.java

Added progress and picture metadata. Some notes:
- Made minor changes to volume calculation/xml printing while testing but should have the same functionality as the existing code
- Progress should work, but the forked-daapd implementation needs to be fixed (seems to be a known issue there). Currently track duration gets passed properly but forked-daapd doesn't reset its current position. Hard coded 44100 as the sample frequency but that can be moved to a constant. Used a value of 1 as an offset for all 3 timestamps because if the first timestamp is 0, it gets skipped by the forked-daapd reader.
- Grabbed the image using okhttp3 as it doesn't seem to be available through mercury
- Added genre but it didn't seem to work so I took it out. Seems like spotify has removed a lot of the genre …

Add progress and picture metadata

---

.travis.yml
.travis/after_script.sh
.travis/before_install.sh
core/src/main/java/xyz/gianlu/librespot/player/Player.java

When using forked-daapd with autostart, the forked-daapd server watches the audio named pipe but doesn't seem to open the metadata pipe until the audio pipe starts playing. Since there is no reader on the metadata named pipe, the librespot-java client blocks on creating the FileOutputStream in the metadataPipe constructor. Initializing the pipe before sending takes care of this.
Moved the sending to threads primarily for the sendImage method as it involves web access.

Runtime init of metadata pipe and threaded send

---

.travis.yml

depends on #190
The build runs implicitely with openjdk11. [job](https://travis-ci.com/github/librespot-org/librespot-java/jobs/300254434#L202)
For better build stability this adds runs with multiple jdks: 8, 11 + latest available (13).
This could allow a smooth transition to newer version of java in the future.

adds build with multiple jdks

---

core/src/main/java/xyz/gianlu/librespot/player/Player.java

If the player is paused mid song while the pipe receiver changes context or reboots, the pipe receiver might forget what is playing. Sending the metadata again when resuming would take care of this.

Send metadata when resuming

---

api/src/main/resources/log4j.properties
core/src/main/resources/log4j.properties

Output now looks like:
```
2020-04-12 21:04:58,164 INFO  Utils:108 - Successfully removed cryptography restrictions.
2020-04-12 21:04:58,430 INFO  ApResolver:66 - Loaded aps into pool: {accesspoint=[guc3-accesspoint-b-6ts2.ap.spotify.com:4070, guc3-accesspoint-b-7d3h.ap.spotify.com:443, guc3-accesspoint-b-wr96.ap.spotify.com:80, guc3-accesspoint-b-slqh.ap.spotify.com:4070, guc3-accesspoint-b-jw6w.ap.spotify.com:443, guc3-accesspoint-b-bknf.ap.spotify.com:80, gae2-accesspoint-b-0fvt.ap.spotify.com:4070, gew1-accesspoint-b-dmwz.ap.spotify.com:443, gew1-accesspoint-b-czzt.ap.spotify.com:80], dealer=[guc-dealer.spotify.com:443, gae-dealer.spotify.com:443, gew-dealer.spotify.com:443], spclient=[guc-spclient.spotify.com:443, gew-spclient.spotify.com:443, gae-spclient.spotify.com:443]} …
```

Changed logging to include milliseconds by default.

---

core/src/main/java/xyz/gianlu/librespot/player/StateWrapper.java

This PR implements updating the queue when moving tracks around in a playing playlist.
I did some basic testing by moving tracks around in a playlist in all the ways I could think of, and it seems to be working fine (lots of trial-and-error though, so no promises :crossed_fingers:).

Implement playlist move tracks

---

common/src/main/java/xyz/gianlu/librespot/common/AsyncWorker.java
core/src/main/java/xyz/gianlu/librespot/core/PacketsManager.java
core/src/main/java/xyz/gianlu/librespot/core/Session.java
core/src/main/java/xyz/gianlu/librespot/core/ZeroconfServer.java
core/src/main/java/xyz/gianlu/librespot/dealer/DealerClient.java
core/src/main/java/xyz/gianlu/librespot/player/Player.java
core/src/main/java/xyz/gianlu/librespot/player/PlayerRunner.java
core/src/main/java/xyz/gianlu/librespot/player/feeders/storage/ChannelManager.java

There are several points where Threads & Executors are not stopped/shutdown once Session.close() is called. This may leave zombie-threads & ongoing threads running if you use librespot-java inside an application.
I was not able to trigger the ChannelManager-methods in any way. Is this dead code or when is the ChannelManager accessed?

Close Threads/Executors on Session.close()

---

core/src/main/java/xyz/gianlu/librespot/player/decrypt/AesAudioDecrypt.java

Since we're calling cipher.init() in every call, there's no need to get the instance every time. Just save it as a private final variable.
In case it ever throws an exception during decoding, running ciper.init() again will bring it to a correct state again (according to the documentation).
This might save us a few ms during playback :)

Do not get a Cipher instance every time we decrypt an AES chunk

---

core/src/main/java/xyz/gianlu/librespot/core/FacebookAuthenticator.java

The credentials json object has no authUsername property, instead it has a username property.

Facebook authentication correction

---

core/src/main/java/xyz/gianlu/librespot/core/Session.java
core/src/main/java/xyz/gianlu/librespot/player/Player.java

In case you lose the network-connection during active playback and call Session.close(), the running threads may block because they wait for a re-connection.
Additionally, an IllegalArgumentException could have been thrown because a playerSession.close(); was missing.

Prevent blocking and IllegalArgumentException while closing session

---

core/src/main/java/xyz/gianlu/librespot/player/mixing/AudioSink.java

Right now, inside the AudioSink, line.start() is called _after_ the first write() to the line.
Depending on the line this may either case errors or the very first audio-package gets lost.
With this PR, the line is acquired and started before the first write, instead before the second write.

Start line before first write to line

---

api/README.md
api/src/main/java/xyz/gianlu/librespot/api/handlers/EventsHandler.java
core/src/main/java/xyz/gianlu/librespot/player/Player.java

Right now it's almost impossible to know if anything goes wrong while playback without checking the logs.
This PR adds an EventsListener.onPanicState().
Maybe you may also publish the information inside the EventsHandler?

Add EventsListener.onPanicState()

---

api/README.md
api/src/main/java/xyz/gianlu/librespot/api/ApiServer.java
api/src/main/java/xyz/gianlu/librespot/api/handlers/ProfileHandler.java
core/src/main/java/xyz/gianlu/librespot/core/TokenProvider.java
core/src/main/java/xyz/gianlu/librespot/mercury/MercuryClient.java
core/src/main/java/xyz/gianlu/librespot/mercury/MercuryRequests.java

This PR adds `/profile/{user_id}/followers` and `/profile/{user_id}/following` to the API.
It can be used to get the users and artists that a specified user is following or followed by.
* Add ability to query followers of profiles
* Add GeneralJson wrapper for generic json responses
* Add statusCode field to MercuryException
* Update README.md

Add Profile Endpoint to API

---

lib/src/main/java/xyz/gianlu/librespot/audio/cdn/CdnManager.java
lib/src/main/java/xyz/gianlu/librespot/audio/storage/AudioFileStreaming.java

+ Added check in CdnManager.java
+ Added check in AudioFileStreaming.java
this commit fixes #252

Added cacheHandler checking

---

api/README.md
api/src/main/java/xyz/gianlu/librespot/api/handlers/PlayerHandler.java
player/src/main/java/xyz/gianlu/librespot/player/Player.java

Fixes https://github.com/librespot-org/librespot-java/issues/272 by allowing a client to increase the volume by 10 steps (or decrease it by 5 steps).
To be discussed:
- I don't accept both `volume` and `step` being present, but we could change this to give precedence to `volume` instead.
- As the player already has volume clamping in its `volumeUp`/`volumeDown` logic, I don't validate that `step` is in any range.
- The player could have a unique `changeVolume(int steps)` method instead of overloading `volumeUp` and `volumeDown`
```
$ curl -X POST -d "step=10" localhost:24879/player/set-volume
$ curl -X POST -d "step=-5" localhost:24879/player/set-volume
$ curl -X POST -d "volume=30000" localhost:24879/player/set-volume
$ curl -X POST -d "step=15&volume=30000" …
```

[api] Allow to set volume as a relative step count

---

lib/src/main/java/xyz/gianlu/librespot/core/Session.java

using a proxy with username and password authentification needing the username:password being base64 encoded
Syntax:
Proxy-Authorization: type credentials
example: 
Proxy-Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l
only credentials have to be encoded, not the whole request. this fix it

proxy authentification fix

---

lib/src/main/java/xyz/gianlu/librespot/ZeroconfServer.java
lib/src/main/java/xyz/gianlu/librespot/core/Session.java

init() already takes care of resetting them to their default state after being used previously.

Removed redundant calls to getInstance()
